name: Manhunt
main: me.gaagjescraft.network.team.manhunt.Manhunt
version: ${project.version}
description: Twisted Manhunt plugin.
author: GCNT
api-version: 1.16
website: https://www.gcnt.net/
depend:
  - WorldEdit
softdepend:
  - CociteSupport
  - Vault
  - ViaVersion
  - NametagEdit
  - Multiverse-Core
  - PlaceholderAPI
  - Chunky
load: POSTWORLD

commands:
  manhuntstats:
    aliases:
      - stats
  manhunt:
    description: Opens the manhunt game menu / managed the game.
  leave:
    aliases:
      - hub
      - quit
    description: Leave your game.
  compass:
    description: Get the compass.
  rejoin:
    description: Rejoin your previous game.