package me.gaagjescraft.network.team.manhunt.utils;

import me.gaagjescraft.network.team.manhunt.Manhunt;
import me.gaagjescraft.network.team.manhunt.games.HeadstartType;
import org.bukkit.Location;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;
import java.util.List;

public class Config {

    private final File file;
    public boolean disableSettingsChanging;
    public boolean bungeeMode;
    public boolean isLobbyServer;
    public String serverName;
    public List<String> gameServers;
    public List<Long> seeds;
    public Location lobby;
    public boolean chatPerTeam;
    public boolean separateDeadChat;
    public boolean joinGameOnServerJoin;
    public boolean teleportLobbyOnServerJoin;
    public boolean announceTwistVoteToEntireGame;
    public String gameJoinMessage;
    public String gameLeftMessage;
    public String gameHostLeftMessage;
    public String playerLeftWaitingMessage;
    public String playerLeftPlayingMessage;
    public List<String> gameEndDrawMessage;
    public String gameEndDrawSound;
    public String gameEndDrawTitle;
    public List<String> gameEndWinMessage;
    public List<String> gameEndLoseMessage;
    public String gameEndWinSound;
    public String gameEndLoseSound;
    public String gameEndWinRunnerDragonTitle;
    public String gameEndWinRunnerTitle;
    public String gameEndWinHunterTitle;
    public String gameEndLoseRunnerTitle;
    public String gameEndLoseHunterTitle;
    public String notIngameMessage;
    public String compassUnavailableMessage;
    public String compassAlreadyAddedMessage;
    public String compassGivenMessage;
    public String lobbySetMessage;
    public String notWhilePlayingMessage;
    public String invalidGameIdMessage;
    public String gameAlreadyStoppingMessage;
    public String gameMustBeWaitingMessage;
    public String gameMustBePlayingMessage;
    public String somethingWentWrong;
    public String commandNoHostMessage;
    public String stoppingGameMessage;
    public String startingGameMessage;
    public String twistAlreadyActiveMessage;
    public String twistForcedMessage;
    public String playerNotOnlineMessage;
    public String playerIsYouMessage;
    public String targetPlayerNotIngameMessage;
    public String targetPlayerAlreadyRunnerMessage;
    public String playerAddRunnerMessage;
    public String playerRemoveRunnerMessage;
    public String targetPlayerNoRunner;
    public String noGameToRejoinMessage;
    public String alreadyInGameRejoinMessage;
    public String rejoinFailMessage;
    public String playerRejoinedMessage;
    public String dragonDefeatedMessage;
    public String dragonDefeatedTitle;
    public String deathTitle;
    public String runnerDownTitle;
    public String runnerDownMessage;
    public String trackerResetDiedMessage;
    public String runnerEnteredNetherSound;
    public String runnerEnteredEndSound;
    public String runnerEnteredNetherMessage;
    public String runnerEnteredEndMessage;
    public String playerEnteredNetherTitle;
    public String playerEnteredEndTitle;
    public String delayedLeaveStartSound;
    public String delayedLeaveStartMessage;
    public String delayedLeaveCancelSound;
    public String delayedLeaveCancelMessage;
    public String playerLeftGameMessage;
    public String trackingActionbar;
    public String trackingOtherDimensionActionbar;
    public String playerTwistVoteMessage;
    public String twistVotedMessage;
    public String runnerAddedMessage;
    public String runnerRemovedMessage;
    public String runnerAddedTitle;
    public String playerRespawnedSound;
    public String respawnedWorldspawnActionbar;
    public String respawnedBedActionbar;
    public String respawnedBedMessage;
    public String respawningSoonTitle;
    public String thanksForPlaying;
    public String countdownSound;
    public String hunterReleaseCountdownMessage;
    public String hunterReleaseCountdownTitle;
    public List<String> huntersReleasedMessage;
    public String startingCountdownMessage;
    public String startingCountdownTitle;
    public String huntersReleasedHunterTitle;
    public String huntersReleasedRunnerTitle;
    public String huntersReleasedSound;
    public String gameStartHunterTitle;
    public String gameStartRunnerTitle;
    public List<String> gameStartRunnerMessage;
    public List<String> gameStartHunterMessage;
    public List<String> twistSelectMessage;
    public String gameCreatedMessage;
    public String alreadyOwnGameMessage;
    public String gameDiscardMessage;
    public String openMenuHostGameSound;
    public String closeMenuHostGameSound;
    public String menuHostToggleTwistSound;
    public String menuHostToggleDaylightSound;
    public String menuHostToggleFriendlyFireSound;
    public String menuHostLockedSound;
    public String menuHostGameStartedSound;
    public String menuTrackerTitle;
    public String menuTeleporterTitle;
    public String menuEventsTitle;
    public String menuHostTitle;
    public String menuGamesTitle;
    public String menuHeadstartTitle;
    public String menuRunnerManagerTitle;
    public String twistRandomYeetSound;
    public String twistSpeedBoostSound;
    public String twistBlindnessSound;
    public String twistAcidRainSound;
    public String twistHardcoreSound;
    public String twistRandomYeetTitle;
    public String twistSpeedBoostTitle;
    public String twistBlindnessTitle;
    public String twistAcidRainTitle;
    public String twistHardcoreTitle;
    public String twistRandomYeetMessage;
    public String twistSpeedBoostMessage;
    public String twistBlindnessMessage;
    public String twistAcidRainMessage;
    public String twistAcidRainEndedMessage;
    public String twistHardcoreMessage;
    public String twistHardcoreEndedMessage;
    public String headstartChangeMessage;
    public String toggleTwistsEnabledMessage;
    public String toggleTwistsDisabledMessage;
    public String toggleDaylightEnabledMessage;
    public String toggleDaylightDisabledMessage;
    public String toggleFriendlyFireEnabledMessage;
    public String toggleFriendlyFireDisabledMessage;
    public String trackingPlayerMessage;
    public String teleportingPlayerMessage;
    public String failedTrackingMessage;
    public String failedTeleportingMessage;
    public String playerIsYouSound;
    public String trackingPlayerSound;
    public String gameUnavailableMessage;
    public String menuHeadstartSelectSound;
    public String menuHeadstartSaveSound;
    public String openMenuHeadstartSound;
    public String menuMaxHuntersChangeAmountSound;
    public String menuMaxHuntersTitle;
    public String runnerAddCancelledMessage;
    public String runnerAddTryAgainMessage;
    public List<String> runnerAddInstructionsMessage;
    public String menuRunnerManagerCannotRemoveHostMessage;
    public String menuRunnerManagerCannotRemoveHostSound;
    public String menuRunnerManagerCannotRemoveRunnerMessage;
    public String menuRunnerManagerCannotRemoveRunnerSound;
    public String runnerRemovedSound;
    public String eventMenuManhuntMaterial;
    public String eventMenuManhuntDisplayname;
    public List<String> eventMenuManhuntLore;
    public String scoreboardTitle;
    public List<String> loadingScoreboard;
    public List<String> waitingScoreboard;
    public List<String> waitingHostScoreboard;
    public List<String> startingRunnerScoreboard;
    public List<String> startingHunterScoreboard;
    public List<String> playingUnreleasedRunnerScoreboard;
    public List<String> playingUnreleasedHunterScoreboard;
    public List<String> playingScoreboard;
    public List<String> stoppingDrawScoreboard;
    public List<String> stoppingWinScoreboard;
    public List<String> stoppingLoseScoreboard;
    public String globalChatPrefix;
    public String runnerChatPrefix;
    public String hunterChatPrefix;
    public String deadChatPrefix;
    public String runnerColor;
    public String hunterColor;
    public String chatFormat;
    public String loadingStatusPrefix;
    public String startingStatusPrefix;
    public String waitingStatusPrefix;
    public String stoppingStatusPrefix;
    public String playingStatusPrefix;
    public String selectedPrefix;
    public String hostMenuTwistEnabledMaterial;
    public String hostMenuTwistEnabledDisplayname;
    public List<String> hostMenuTwistEnabledLore;
    public String hostMenuTwistDisabledMaterial;
    public String hostMenuTwistDisabledDisplayname;
    public List<String> hostMenuTwistDisabledLore;
    public String hostMenuDaylightCycleEnabledMaterial;
    public String hostMenuDaylightCycleDisabledMaterial;
    public String hostMenuDaylightCycleEnabledDisplayname;
    public String hostMenuDaylightCycleDisabledDisplayname;
    public List<String> hostMenuDaylightCycleDisabledLore;
    public List<String> hostMenuDaylightCycleEnabledLore;
    public String hostMenuHeadstartMaterial;
    public String hostMenuHeadstartDisplayname;
    public List<String> hostMenuHeadstartLockedLore;
    public List<String> hostMenuHeadstartLore;
    public String hostMenuManageRunnersMaterial;
    public String hostMenuManageRunnersDisplayname;
    public List<String> hostMenuManageRunnersLore;
    public List<String> hostMenuManageRunnersLockedLore;
    public String hostMenuFriendlyFireEnabledMaterial;
    public String hostMenuFriendlyFireDisabledMaterial;
    public String hostMenuFriendlyFireEnabledDisplayname;
    public String hostMenuFriendlyFireDisabledDisplayname;
    public List<String> hostMenuFriendlyFireEnabledLore;
    public List<String> hostMenuFriendlyFireDisabledLore;
    public String hostMenuPlayerAmountMaterial;
    public String hostMenuPlayerAmountDisplayname;
    public List<String> hostMenuPlayerAmountLockedLore;
    public List<String> hostMenuPlayerAmountLore;
    public String gamesMenuGameHostDisplayname;
    public List<String> gamesMenuGameHostLore;
    public List<String> gamesMenuGameHostLockedLore;
    public String headstartMenuHalfMinuteHeadstartMaterial;
    public String headstartMenuHalfMinuteHeadstartDisplayname;
    public String headstartMenuOneMinuteHeadstartMaterial;
    public String headstartMenuOneMinuteHeadstartDisplayname;
    public String headstartMenuOneHalfMinuteHeadstartMaterial;
    public String headstartMenuOneHalfMinuteHeadstartDisplayname;
    public String headstartMenuTwoMinutesHeadstartMaterial;
    public String headstartMenuTwoMinutesHeadstartDisplayname;
    public List<String> headstartMenuHeadstartLore;
    public String headstartMenuSaveMaterial;
    public String headstartMenuSaveDisplayname;
    public List<String> headstartMenuSaveLore;
    public String maxHuntersMenuSaveMaterial;
    public String maxHuntersMenuSaveDisplayname;
    public List<String> maxHuntersMenuSaveLore;
    public String maxHuntersMenuAddDisplayname;
    public List<String> maxHuntersMenuAddLore;
    public String maxHuntersMenuRemoveDisplayname;
    public List<String> maxHuntersMenuRemoveLore;
    public String runnerManagerMenuGeneralRunnerDisplayname;
    public List<String> runnerManagerMenuGeneralRunnerLore;
    public String runnerManagerMenuHostRunnerDisplayname;
    public List<String> runnerManagerMenuHostRunnerLore;
    public String runnerManagerMenuAddRunnerMaterial;
    public String runnerManagerMenuAddRunnerDisplayname;
    public List<String> runnerManagerMenuAddRunnerLore;
    public String runnerManagerMenuSaveMaterial;
    public String runnerManagerMenuSaveDisplayname;
    public List<String> runnerManagerMenuSaveLore;
    public String twistVoteMenuHardcoreMaterial;
    public String twistVoteMenuHardcoreDisplayname;
    public List<String> twistVoteMenuHardcoreLore;
    public String twistVoteMenuExtraHealthMaterial;
    public String twistVoteMenuExtraHealthDisplayname;
    public List<String> twistVoteMenuExtraHealthLore;
    public String twistVoteMenuBlindnessMaterial;
    public String twistVoteMenuBlindnessDisplayname;
    public List<String> twistVoteMenuBlindnessLore;
    public String twistVoteMenuRandomYeetMaterial;
    public String twistVoteMenuRandomYeetDisplayname;
    public List<String> twistVoteMenuRandomYeetLore;
    public String twistVoteMenuSpeedBoostMaterial;
    public String twistVoteMenuSpeedBoostDisplayname;
    public List<String> twistVoteMenuSpeedBoostLore;
    public String twistVoteMenuNoneMaterial;
    public String twistVoteMenuNoneDisplayname;
    public List<String> twistVoteMenuNoneLore;
    public String twistVoteMenuAcidRainMaterial;
    public String twistVoteMenuAcidRainDisplayname;
    public List<String> twistvoteMenuAcidRainLore;
    public String menuTwistVoteTitle;
    public String openTwistVoteMenuSound;
    public String twistVoteSound;
    public String teleporterMenuPlayerDisplayname;
    public List<String> teleporterMenuPlayerLore;
    public String trackerMenuPlayerDisplayname;
    public List<String> trackerMenuPlayerLore;
    public String generalFillMaterial;
    public String generalCloseMaterial;
    public String gamesMenuNoGamesMaterial;
    public String gamesMenuHostGameMaterial;
    public String gamesMenuHostUnsupportedProtocolMaterial;
    public String hostMenuFinishMaterial;
    public String hostMenuStartMaterial;
    public String generalTrackerMaterial;
    public String generalLeaveMaterial;
    public String generalTwistVoteMaterial;
    public String generalSettingsMaterial;
    public String generalCloseDisplayname;
    public String gamesMenuNoGamesDisplayname;
    public String gamesMenuHostGameDisplayname;
    public String gamesMenuHostUnsupportedProtocolDisplayname;
    public String hostMenuFinishDisplayname;
    public String hostMenuStartDisplayname;
    public String generalTrackerDisplayname;
    public String generalLeaveDisplayname;
    public String generalTwistVoteDisplayname;
    public String generalSettingsDisplayname;
    public List<String> generalCloseLore;
    public List<String> gamesMenuNoGamesLore;
    public List<String> gamesMenuHostGameLore;
    public List<String> gamesMenuHostUnsupportedProtocolLore;
    public List<String> hostMenuFinishLore;
    public List<String> hostMenuStartLore;
    public List<String> generalTrackerLore;
    public List<String> generalLeaveLore;
    public List<String> generalTwistVoteLore;
    public List<String> generalSettingsLore;
    public boolean teleportPlayersToLobbyInVoid;
    public String cannotLeaveWaitingZoneMessage;
    public String cannotLeaveLobbyMessage;
    public List<String> autoRejoinMessage;
    public boolean autoJoinOnlinePlayersWhenGameCreated;
    public int gensizechunks;
    public String runnerNametagPrefix;
    public String hunterNametagPrefix;
    public List<String> statsMessage;
    public boolean enableLobbyChat;
    public String lobbyChatPrefix;
    public String lobbyChatFormat;
    public String spectatorChatColor;
    public boolean spectatorsHaveGeneralColor;
    public String trackingPortalActionbar;
    public String storageType;
    public String databaseHostname;
    public String databaseUsername;
    public String databasePassword;
    public String databaseDatabase;
    public String socketHostname;
    public int socketPort;
    public String lobbyServerName;
    public int minimumClientProtocolVersion;
    public boolean defaultOptionAllowTwists;
    public int defaultOptionMaxPlayers;
    public boolean defaultOptionAllowFriendlyFire;
    public boolean defaultOptionDoDaylightCycle;
    public HeadstartType defaultOptionHeadstart;
    public String joinFailMessage;
    public boolean debug;
    public String moneyRefundedMessage;
    public int pricePerGame;
    public boolean sendGameHostAnnouncement;
    public String gameHostAnnouncementSound;
    public String gameHostAnnouncementMessage;
    public List<String> killRewards;
    public List<String> winRewards;
    public List<String> loseRewards;
    public List<String> topThreeRewards;
    public String newHostAssignedMessage;
    public String newHostAssignedTitle;
    public String newHostAssignedSound;
    public String searchingServerTitle;
    public String noServersAvailableTitle;
    public String noServersAvailableMessage;
    public String moneyRefundedNoServersMessage;
    public String noServersAvailableSound;
    public String searchingServerTickingSound;
    public String gameSubmittedMessage;
    public String freeGameHostedMessage;
    public String moneyPaidHostingGameMessage;
    public String notEnoughMoneyHostingGameMessage;
    public String noPermissionHostingGameMessage;
    public String cantHostGameSound;
    public String mainMenuTitle;
    public String mainMenuBalanceInfoEnoughMaterial;
    public String mainMenuBalanceInfoEnoughDisplayname;
    public List<String> mainMenuBalanceInfoEnoughLore;
    public String mainMenuBalanceInfoNotEnoughMaterial;
    public String mainMenuBalanceInfoNotEnoughDisplayname;
    public List<String> mainMenuBalanceInfoNotEnoughLore;
    public String mainMenuHostGameCanHostMaterial;
    public String mainMenuHostGameCanHostDisplayname;
    public List<String> mainMenuHostGameCanHostLore;
    public String mainMenuHostGameCannotHostMaterial;
    public String mainMenuHostGameCannotHostDisplayname;
    public List<String> mainMenuHostGameCannotHostLore;
    public String mainMenuHostGameInvalidVersionMaterial;
    public String mainMenuHostGameInvalidVersionDisplayname;
    public List<String> mainMenuHostGameInvalidVersionLore;
    public String mainMenuJoinGameMaterial;
    public String mainMenuJoinGameDisplayname;
    public List<String> mainMenuJoinGameLore;
    public String mainMenuJoinGameInvalidVersionMaterial;
    public String mainMenuJoinGameInvalidVersionDisplayname;
    public List<String> mainMenuJoinGameInvalidVersionLore;
    public String mainMenuStoreMaterial;
    public String mainMenuStoreDisplayname;
    public List<String> mainMenuStoreLore;
    public String mainMenuClickStoreItemSound;
    public String mainMenuClickStoreItemMessage;
    public String cannotHostGameInvalidVersionMessage;
    public String cannotJoinGameInvalidVersionMessage;
    public String twistVoteMenuOptionDisabledMaterial;
    public String twistVoteMenuOptionDisabledDisplayname;
    public List<String> twistVoteMenuOptionDisabledLore;
    public String generalGoBackMaterial;
    public String generalGoBackDisplayname;
    public List<String> generalGoBackLore;
    public String serverFoundTitle;
    public List<String> serverFoundMessage;
    public List<String> creatingGameErrorMessage;
    public String finishedPreparingServerMessage;
    public boolean stopServerAfterGame;
    public boolean enableWorldBorder;
    public double worldBorderSize;
    public double worldBorderDamage;
    public double worldBorderDamageBuffer;
    public int worldBorderWarningDistance;
    public int worldBorderWarningTime;
    public int lobbyTeleportYCoord;
    public boolean cancelLobbyInteractions;
    public boolean sendGameHostAnnouncementToLobbyOnly;
    public String revivedPlayerMessage;
    public String addLifeMessage;
    public String removeLifeMessage;

    public int minimumPlayers;
    public int maximumPlayers;
    public int hunterLives;
    public boolean useUuidsAsWorldNames;
    public boolean disableAdvancementAnnouncing;


    private FileConfiguration conf;


    public Config() {
        file = new File(Manhunt.get().getDataFolder(), "config.yml");
        if (!file.exists()) {
            Manhunt.get().saveResource("config.yml", false);
        }
        Manhunt.get().getConfig().options().copyDefaults(true);
        Manhunt.get().saveDefaultConfig();
        Manhunt.get().saveConfig();
        Manhunt.get().reloadConfig();

        load();
        save();
    }

    public void load() {
        conf = YamlConfiguration.loadConfiguration(file);
        conf.options().copyDefaults(true);

        this.disableSettingsChanging = conf.getBoolean("disable_setting_changing", false);
        this.bungeeMode = conf.getBoolean("bungee.enabled", false);
        this.isLobbyServer = conf.getBoolean("bungee.is-lobby", false);
        this.serverName = conf.getString("bungee.server-name", "manhunt-1");
        this.gameServers = conf.getStringList("bungee.game-servers");
        this.socketHostname = conf.getString("bungee.socket.hostname");
        this.socketPort = conf.getInt("bungee.socket.port");
        this.lobbyServerName = conf.getString("bungee.lobby-server-name");
        this.teleportLobbyOnServerJoin = conf.getBoolean("teleport-lobby-on-server-join");
        this.joinGameOnServerJoin = conf.getBoolean("join-game-on-server-join");
        this.announceTwistVoteToEntireGame = conf.getBoolean("announce-twist-vote-to-entire-game");
        this.teleportPlayersToLobbyInVoid = conf.getBoolean("teleport-players-to-lobby-in-void");
        this.lobbyTeleportYCoord = conf.getInt("lobby-teleport-void-y-coord");
        this.autoJoinOnlinePlayersWhenGameCreated = conf.getBoolean("auto-join-online-players-when-game-created");
        this.gensizechunks = conf.getInt("chunky-generation-size");
        this.minimumClientProtocolVersion = conf.getInt("minimum_client_protocol_version");
        this.debug = conf.getBoolean("debug");
        this.pricePerGame = conf.getInt("price-per-game");
        this.sendGameHostAnnouncement = conf.getBoolean("send-game-host-announcement");
        this.sendGameHostAnnouncementToLobbyOnly = conf.getBoolean("send-game-announcement-to-lobby-only");
        this.killRewards = conf.getStringList("rewards.kill");
        this.winRewards = conf.getStringList("rewards.win");
        this.loseRewards = conf.getStringList("rewards.lose");
        this.topThreeRewards = conf.getStringList("rewards.top-three");
        this.stopServerAfterGame = conf.getBoolean("stop-server-after-game");
        this.minimumPlayers = conf.getInt("minimum-players-per-game");
        this.maximumPlayers = conf.getInt("maximum-players-per-game");
        this.hunterLives = conf.getInt("hunter-lives");
        this.useUuidsAsWorldNames = conf.getBoolean("use-uuids-as-world-names");
        this.disableAdvancementAnnouncing = conf.getBoolean("disable-advancement-announcing");
        this.cancelLobbyInteractions = conf.getBoolean("cancel-lobby-interactions");

        this.defaultOptionAllowTwists = conf.getBoolean("default_settings.allow_twists");
        this.defaultOptionMaxPlayers = conf.getInt("default_settings.max_players");
        this.defaultOptionAllowFriendlyFire = conf.getBoolean("default_settings.allow_friendly_fire");
        this.defaultOptionDoDaylightCycle = conf.getBoolean("default_settings.do_daylight_cycle");
        this.defaultOptionHeadstart = HeadstartType.valueOf(conf.getString("default_settings.headstart", "HALF_MINUTE"));

        this.seeds = conf.getLongList("seeds");
        this.lobby = conf.getLocation("lobby");

        this.storageType = conf.getString("storage.type");
        this.databaseHostname = conf.getString("storage.database.hostname");
        this.databaseUsername = conf.getString("storage.database.username");
        this.databasePassword = conf.getString("storage.database.password");
        this.databaseDatabase = conf.getString("storage.database.database");

        this.enableWorldBorder = conf.getBoolean("world-border.enable");
        this.worldBorderSize = conf.getDouble("world-border.size");
        this.worldBorderDamage = conf.getDouble("world-border.damage-amount");
        this.worldBorderDamageBuffer = conf.getDouble("world-border.damage-buffer");
        this.worldBorderWarningDistance = conf.getInt("world-border.warning-distance");
        this.worldBorderWarningTime = conf.getInt("world-border.warning-time");

        this.enableLobbyChat = conf.getBoolean("chat.enable-lobby-chat");
        this.chatPerTeam = conf.getBoolean("chat.per-team");
        this.separateDeadChat = conf.getBoolean("chat.separate-dead-chat");
        this.chatFormat = conf.getString("chat.format");
        this.lobbyChatFormat = conf.getString("chat.lobby-format");
        this.spectatorsHaveGeneralColor = conf.getBoolean("chat.spectators-have-general-color");

        this.addLifeMessage = conf.getString("messages.addlife-player");
        this.removeLifeMessage = conf.getString("messages.removelife-player");
        this.revivedPlayerMessage = conf.getString("messages.revived-player");
        this.finishedPreparingServerMessage = conf.getString("messages.finished-preparing-server");
        this.serverFoundMessage = conf.getStringList("messages.server-found");
        this.creatingGameErrorMessage = conf.getStringList("messages.creating-game-error");
        this.cannotHostGameInvalidVersionMessage = conf.getString("messages.cannot-host-game-invalid-version");
        this.cannotJoinGameInvalidVersionMessage = conf.getString("messages.cannot-join-game-invalid-version");
        this.mainMenuClickStoreItemMessage = conf.getString("messages.main-menu-click-store-item");
        this.gameSubmittedMessage = conf.getString("messages.game-submitted");
        this.freeGameHostedMessage = conf.getString("messages.free-game-hosted");
        this.moneyPaidHostingGameMessage = conf.getString("messages.money-paid-hosting-game");
        this.notEnoughMoneyHostingGameMessage = conf.getString("messages.not-enough-money-hosting-game");
        this.noPermissionHostingGameMessage = conf.getString("messages.no-permission-hosting-game");
        this.moneyRefundedNoServersMessage = conf.getString("messages.money-refunded-no-servers");
        this.noServersAvailableMessage = conf.getString("messages.no-servers-available");
        this.newHostAssignedMessage = conf.getString("messages.new-host-assigned");
        this.gameHostAnnouncementMessage = conf.getString("messages.game-host-announcement");
        this.joinFailMessage = conf.getString("messages.join-fail");
        this.gameJoinMessage = conf.getString("messages.game-joined");
        this.gameLeftMessage = conf.getString("messages.game-left");
        this.gameHostLeftMessage = conf.getString("messages.game-host-left");
        this.playerLeftPlayingMessage = conf.getString("messages.player-left-playing");
        this.playerLeftWaitingMessage = conf.getString("messages.player-left-waiting");
        this.gameEndWinMessage = conf.getStringList("messages.game-end.win");
        this.gameEndLoseMessage = conf.getStringList("messages.game-end.lose");
        this.gameEndDrawMessage = conf.getStringList("messages.game-end.draw");
        this.notIngameMessage = conf.getString("messages.not-ingame");
        this.compassUnavailableMessage = conf.getString("messages.compass-unavailable");
        this.compassAlreadyAddedMessage = conf.getString("messages.compass-already-added");
        this.compassGivenMessage = conf.getString("messages.compass-given");
        this.lobbySetMessage = conf.getString("messages.lobby-set");
        this.notWhilePlayingMessage = conf.getString("messages.not-while-playing");
        this.invalidGameIdMessage = conf.getString("messages.invalid-game-id");
        this.gameAlreadyStoppingMessage = conf.getString("messages.game-already-stopping");
        this.gameMustBeWaitingMessage = conf.getString("messages.game-must-be-waiting");
        this.gameMustBePlayingMessage = conf.getString("messages.game-must-be-playing");
        this.somethingWentWrong = conf.getString("messages.something-went-wrong");
        this.commandNoHostMessage = conf.getString("messages.command-no-host");
        this.stoppingGameMessage = conf.getString("messages.stopping-game");
        this.startingGameMessage = conf.getString("messages.starting-game");
        this.twistAlreadyActiveMessage = conf.getString("messages.twist-already-active");
        this.twistForcedMessage = conf.getString("messages.force-started-twist");
        this.playerNotOnlineMessage = conf.getString("messages.player-not-online");
        this.playerIsYouMessage = conf.getString("messages.player-is-you");
        this.targetPlayerNotIngameMessage = conf.getString("messages.target-player-not-ingame");
        this.targetPlayerAlreadyRunnerMessage = conf.getString("messages.target-player-already-runner");
        this.playerAddRunnerMessage = conf.getString("messages.player-addrunner");
        this.playerRemoveRunnerMessage = conf.getString("messages.player-removerunner");
        this.targetPlayerNoRunner = conf.getString("messages.target-player-no-runner");
        this.noGameToRejoinMessage = conf.getString("messages.no-game-to-rejoin");
        this.alreadyInGameRejoinMessage = conf.getString("messages.already-in-game-rejoin");
        this.rejoinFailMessage = conf.getString("messages.rejoin-fail");
        this.playerRejoinedMessage = conf.getString("messages.player-rejoined");
        this.dragonDefeatedMessage = conf.getString("messages.dragon-defeated");
        this.runnerDownTitle = conf.getString("messages.runner-down");
        this.trackerResetDiedMessage = conf.getString("messages.tracker-reset-died");
        this.runnerEnteredNetherMessage = conf.getString("messages.runner-entered-nether");
        this.runnerEnteredEndMessage = conf.getString("messages.runner-entered-end");
        this.delayedLeaveCancelMessage = conf.getString("messages.delayed-leave-cancel");
        this.delayedLeaveStartMessage = conf.getString("messages.delayed-leave-start");
        this.playerLeftGameMessage = conf.getString("messages.player-left-game");
        this.playerTwistVoteMessage = conf.getString("messages.player-twist-voted");
        this.twistVotedMessage = conf.getString("messages.twist-voted");
        this.runnerAddedMessage = conf.getString("messages.runner-added");
        this.runnerRemovedMessage = conf.getString("messages.runner-removed");
        this.respawnedBedMessage = conf.getString("messages.respawned-bed");
        this.thanksForPlaying = conf.getString("messages.thanks-for-playing");
        this.hunterReleaseCountdownMessage = conf.getString("messages.hunter-release-countdown");
        this.startingCountdownMessage = conf.getString("messages.starting-countdown");
        this.huntersReleasedMessage = conf.getStringList("messages.hunters-released");
        this.gameStartRunnerMessage = conf.getStringList("messages.game-start-runner");
        this.gameStartHunterMessage = conf.getStringList("messages.game-start-hunter");
        this.twistSelectMessage = conf.getStringList("messages.twist-select");
        this.twistRandomYeetMessage = conf.getString("messages.twists.random-yeet");
        this.twistSpeedBoostMessage = conf.getString("messages.twists.speed-boost");
        this.twistBlindnessMessage = conf.getString("messages.twists.blindness");
        this.twistAcidRainMessage = conf.getString("messages.twists.acid-rain");
        this.twistAcidRainEndedMessage = conf.getString("messages.twists.acid-rain-ended");
        this.twistHardcoreMessage = conf.getString("messages.twists.hardcore");
        this.twistHardcoreEndedMessage = conf.getString("messages.twists.hardcore-ended");
        this.headstartChangeMessage = conf.getString("messages.headstart-change");
        this.toggleTwistsEnabledMessage = conf.getString("messages.toggle-twists-enabled");
        this.toggleTwistsDisabledMessage = conf.getString("messages.toggle-twists-disabled");
        this.toggleDaylightEnabledMessage = conf.getString("messages.toggle-daylight-enabled");
        this.toggleDaylightDisabledMessage = conf.getString("messages.toggle-daylight-disabled");
        this.toggleFriendlyFireEnabledMessage = conf.getString("messages.toggle-friendly-fire-enabled");
        this.toggleFriendlyFireDisabledMessage = conf.getString("messages.toggle-friendly-fire-disabled");
        this.trackingPlayerMessage = conf.getString("messages.tracking-player");
        this.teleportingPlayerMessage = conf.getString("messages.teleporting-player");
        this.failedTrackingMessage = conf.getString("messages.failed-tracking");
        this.failedTeleportingMessage = conf.getString("messages.failed-teleporting");
        this.gameCreatedMessage = conf.getString("messages.game-created");
        this.alreadyOwnGameMessage = conf.getString("messages.already-own-game");
        this.gameDiscardMessage = conf.getString("messages.game-discard");
        this.gameUnavailableMessage = conf.getString("messages.game-unavailable");
        this.runnerAddCancelledMessage = conf.getString("messages.runner-add-cancelled");
        this.runnerAddTryAgainMessage = conf.getString("messages.runner-add-try-again");
        this.runnerAddInstructionsMessage = conf.getStringList("messages.runner-add-instructions");
        this.menuRunnerManagerCannotRemoveHostMessage = conf.getString("messages.menu-runner-manager-cannot-remove-host");
        this.menuRunnerManagerCannotRemoveRunnerMessage = conf.getString("messages.menu-runner-manager-cannot-remove-runner");
        this.cannotLeaveLobbyMessage = conf.getString("messages.cannot-leave-lobby");
        this.cannotLeaveWaitingZoneMessage = conf.getString("messages.cannot-leave-waiting-zone");
        this.autoRejoinMessage = conf.getStringList("messages.auto-rejoin");
        this.runnerDownMessage = conf.getString("messages.runner-down");
        this.statsMessage = conf.getStringList("messages.stats-message");
        this.moneyRefundedMessage = conf.getString("messages.money-refunded");

        this.menuTrackerTitle = conf.getString("menus.tracker-title");
        this.menuTeleporterTitle = conf.getString("menus.teleporter-title");
        this.menuEventsTitle = conf.getString("menus.events-title");
        this.menuHostTitle = conf.getString("menus.host-title");
        this.menuGamesTitle = conf.getString("menus.games-title");
        this.menuHeadstartTitle = conf.getString("menus.headstart-title");
        this.menuMaxHuntersTitle = conf.getString("menus.max-hunters-title");
        this.menuRunnerManagerTitle = conf.getString("menus.runner-manager-title");
        this.menuTwistVoteTitle = conf.getString("menus.twist-vote-title");
        this.mainMenuTitle = conf.getString("menus.main-title");

        this.runnerNametagPrefix = conf.getString("prefixes.nametags.runner");
        this.hunterNametagPrefix = conf.getString("prefixes.nametags.hunter");
        this.lobbyChatPrefix = conf.getString("prefixes.lobby");
        this.globalChatPrefix = conf.getString("prefixes.global");
        this.runnerChatPrefix = conf.getString("prefixes.runner");
        this.hunterChatPrefix = conf.getString("prefixes.hunter");
        this.deadChatPrefix = conf.getString("prefixes.dead");
        this.runnerColor = conf.getString("prefixes.runner-color");
        this.hunterColor = conf.getString("prefixes.hunter-color");
        this.spectatorChatColor = conf.getString("prefixes.spectator-color");
        this.loadingStatusPrefix = conf.getString("prefixes.status.loading");
        this.startingStatusPrefix = conf.getString("prefixes.status.starting");
        this.waitingStatusPrefix = conf.getString("prefixes.status.waiting");
        this.stoppingStatusPrefix = conf.getString("prefixes.status.stopping");
        this.playingStatusPrefix = conf.getString("prefixes.status.playing");
        this.selectedPrefix = conf.getString("prefixes.selected");

        this.trackingPortalActionbar = conf.getString("actionbar.tracking-portal");
        this.trackingActionbar = conf.getString("actionbar.tracking");
        this.trackingOtherDimensionActionbar = conf.getString("actionbar.tracking-other-dimension");
        this.respawnedWorldspawnActionbar = conf.getString("actionbar.respawned-worldspawn");
        this.respawnedBedActionbar = conf.getString("actionbar.respawned-bed");

        this.serverFoundTitle = conf.getString("titles.server-found");
        this.searchingServerTitle = conf.getString("titles.searching-server");
        this.noServersAvailableTitle = conf.getString("titles.no-servers-available");
        this.newHostAssignedTitle = conf.getString("titles.new-host-assigned");
        this.gameEndDrawTitle = conf.getString("titles.game-end.draw");
        this.gameEndWinHunterTitle = conf.getString("titles.game-end.win-hunter");
        this.gameEndWinRunnerTitle = conf.getString("titles.game-end.win-runner");
        this.gameEndLoseHunterTitle = conf.getString("titles.game-end.lose-hunter");
        this.gameEndLoseRunnerTitle = conf.getString("titles.game-end.lose-runner");
        this.gameEndWinRunnerDragonTitle = conf.getString("titles.game-end.win-runner-dragon");
        this.dragonDefeatedTitle = conf.getString("titles.dragon-defeated");
        this.deathTitle = conf.getString("titles.death");
        this.runnerDownTitle = conf.getString("titles.runner-down");
        this.playerEnteredNetherTitle = conf.getString("titles.player-entered-nether");
        this.playerEnteredEndTitle = conf.getString("titles.player-entered-end");
        this.runnerAddedTitle = conf.getString("titles.runner-added");
        this.respawningSoonTitle = conf.getString("titles.respawning-soon");
        this.hunterReleaseCountdownTitle = conf.getString("titles.hunter-release-countdown");
        this.huntersReleasedHunterTitle = conf.getString("titles.hunters-released-hunter");
        this.huntersReleasedRunnerTitle = conf.getString("titles.hunters-released-runner");
        this.startingCountdownTitle = conf.getString("titles.starting-countdown");
        this.gameStartHunterTitle = conf.getString("titles.game-start-hunter");
        this.gameStartRunnerTitle = conf.getString("titles.game-start-runner");
        this.twistRandomYeetTitle = conf.getString("titles.twists.random-yeet");
        this.twistSpeedBoostTitle = conf.getString("titles.twists.speed-boost");
        this.twistBlindnessTitle = conf.getString("titles.twists.blindness");
        this.twistAcidRainTitle = conf.getString("titles.twists.acid-rain");
        this.twistHardcoreTitle = conf.getString("titles.twists.hardcore");

        this.scoreboardTitle = conf.getString("scoreboards.title");
        this.loadingScoreboard = conf.getStringList("scoreboards.loading");
        this.waitingScoreboard = conf.getStringList("scoreboards.waiting");
        this.waitingHostScoreboard = conf.getStringList("scoreboards.waiting-host");
        this.startingRunnerScoreboard = conf.getStringList("scoreboards.starting-runner");
        this.startingHunterScoreboard = conf.getStringList("scoreboards.starting-hunter");
        this.playingUnreleasedRunnerScoreboard = conf.getStringList("scoreboards.playing-unreleased-runner");
        this.playingUnreleasedHunterScoreboard = conf.getStringList("scoreboards.playing-unreleased-hunter");
        this.playingScoreboard = conf.getStringList("scoreboards.playing");
        this.stoppingDrawScoreboard = conf.getStringList("scoreboards.stopping-draw");
        this.stoppingWinScoreboard = conf.getStringList("scoreboards.stopping-win");
        this.stoppingLoseScoreboard = conf.getStringList("scoreboards.stopping-lose");

        this.cantHostGameSound = conf.getString("sounds.cant-host-game");
        this.searchingServerTickingSound = conf.getString("sounds.searching-server-ticking");
        this.noServersAvailableSound = conf.getString("sounds.no-servers-available");
        this.newHostAssignedSound = conf.getString("sounds.new-host-assigned");
        this.gameHostAnnouncementSound = conf.getString("sounds.game-host-announcement");
        this.gameEndDrawSound = conf.getString("sounds.game-end.draw");
        this.gameEndWinSound = conf.getString("sounds.game-end.win");
        this.gameEndLoseSound = conf.getString("sounds.game-end.lose");
        this.runnerEnteredNetherSound = conf.getString("sounds.runner-entered-nether");
        this.runnerEnteredEndSound = conf.getString("sounds.runner-entered-end");
        this.delayedLeaveStartSound = conf.getString("sounds.delayed-leave-start");
        this.delayedLeaveCancelSound = conf.getString("sounds.delayed-leave-cancel");
        this.playerRespawnedSound = conf.getString("sounds.player-respawned");
        this.countdownSound = conf.getString("sounds.countdown");
        this.huntersReleasedSound = conf.getString("sounds.hunters-released");
        this.twistRandomYeetSound = conf.getString("sounds.twists.random-yeet");
        this.twistSpeedBoostSound = conf.getString("sounds.twists.speed-boost");
        this.twistBlindnessSound = conf.getString("sounds.twists.blindness");
        this.twistAcidRainSound = conf.getString("sounds.twists.acid-rain");
        this.twistHardcoreSound = conf.getString("sounds.twists.hardcore");
        this.playerIsYouSound = conf.getString("sounds.player-is-you");
        this.trackingPlayerSound = conf.getString("sounds.tracking-player");
        this.openMenuHostGameSound = conf.getString("sounds.open-menu-host-game");
        this.closeMenuHostGameSound = conf.getString("sounds.close-menu-host-game");
        this.menuHostToggleTwistSound = conf.getString("sounds.menu-host-toggle-twist");
        this.menuHostToggleDaylightSound = conf.getString("sounds.menu-host-toggle-daylight");
        this.menuHostToggleFriendlyFireSound = conf.getString("sounds.menu-host-toggle-friendly-fire");
        this.menuHostLockedSound = conf.getString("sounds.menu-host-locked");
        this.menuHostGameStartedSound = conf.getString("sounds.menu-host-game-started");
        this.menuHeadstartSaveSound = conf.getString("sounds.menu-headstart-save");
        this.menuHeadstartSelectSound = conf.getString("sounds.menu-headstart-select");
        this.openMenuHeadstartSound = conf.getString("sounds.open-menu-headstart");
        this.menuMaxHuntersChangeAmountSound = conf.getString("sounds.menu-max-hunters-change-amount");
        this.menuRunnerManagerCannotRemoveHostSound = conf.getString("sounds.menu-runner-manager-cannot-remove-host");
        this.menuRunnerManagerCannotRemoveRunnerSound = conf.getString("sounds.menu-runner-manager-cannot-remove-runner");
        this.runnerRemovedSound = conf.getString("sounds.runner-removed");
        this.twistVoteSound = conf.getString("sounds.twist-vote");
        this.openTwistVoteMenuSound = conf.getString("sounds.open-twist-vote-menu");
        this.mainMenuClickStoreItemSound = conf.getString("sounds.main-menu-click-store-item");

        generalGoBackMaterial = conf.getString("items.general.go-back-material");
        generalGoBackDisplayname = conf.getString("items.general.go-back-displayname");
        generalGoBackLore = conf.getStringList("items.general.go-back-lore");
        twistVoteMenuOptionDisabledMaterial = conf.getString("items.twist-vote-menu.option-disabled-material");
        twistVoteMenuOptionDisabledDisplayname = conf.getString("items.twist-vote-menu.option-disabled-displayname");
        twistVoteMenuOptionDisabledLore = conf.getStringList("items.twist-vote-menu.option-disabled-lore");

        mainMenuHostGameCanHostMaterial = conf.getString("items.main-menu.host-game-can-host-material");
        mainMenuHostGameCanHostDisplayname = conf.getString("items.main-menu.host-game-can-host-displayname");
        mainMenuHostGameCanHostLore = conf.getStringList("items.main-menu.host-game-can-host-lore");
        mainMenuHostGameCannotHostMaterial = conf.getString("items.main-menu.host-game-cannot-host-material");
        mainMenuHostGameCannotHostDisplayname = conf.getString("items.main-menu.host-game-cannot-host-displayname");
        mainMenuHostGameCannotHostLore = conf.getStringList("items.main-menu.host-game-cannot-host-lore");
        mainMenuHostGameInvalidVersionMaterial = conf.getString("items.main-menu.host-game-invalid-version-material");
        mainMenuHostGameInvalidVersionDisplayname = conf.getString("items.main-menu.host-game-invalid-version-displayname");
        mainMenuHostGameInvalidVersionLore = conf.getStringList("items.main-menu.host-game-invalid-version-lore");
        mainMenuJoinGameMaterial = conf.getString("items.main-menu.join-game-material");
        mainMenuJoinGameDisplayname = conf.getString("items.main-menu.join-game-displayname");
        mainMenuJoinGameLore = conf.getStringList("items.main-menu.join-game-lore");
        mainMenuJoinGameInvalidVersionMaterial = conf.getString("items.main-menu.join-game-invalid-version-material");
        mainMenuJoinGameInvalidVersionDisplayname = conf.getString("items.main-menu.join-game-invalid-version-displayname");
        mainMenuJoinGameInvalidVersionLore = conf.getStringList("items.main-menu.join-game-invalid-version-lore");
        mainMenuStoreMaterial = conf.getString("items.main-menu.store-material");
        mainMenuStoreDisplayname = conf.getString("items.main-menu.store-displayname");
        mainMenuStoreLore = conf.getStringList("items.main-menu.store-lore");
        mainMenuBalanceInfoEnoughMaterial = conf.getString("items.main-menu.balance-info-enough-material");
        mainMenuBalanceInfoEnoughDisplayname = conf.getString("items.main-menu.balance-info-enough-displayname");
        mainMenuBalanceInfoEnoughLore = conf.getStringList("items.main-menu.balance-info-enough-lore");
        mainMenuBalanceInfoNotEnoughMaterial = conf.getString("items.main-menu.balance-info-not-enough-material");
        mainMenuBalanceInfoNotEnoughDisplayname = conf.getString("items.main-menu.balance-info-not-enough-displayname");
        mainMenuBalanceInfoNotEnoughLore = conf.getStringList("items.main-menu.balance-info-not-enough-lore");
        eventMenuManhuntMaterial = conf.getString("items.event-menu.manhunt-material");
        eventMenuManhuntDisplayname = conf.getString("items.event-menu.manhunt-displayname");
        eventMenuManhuntLore = conf.getStringList("items.event-menu.manhunt-lore");
        hostMenuTwistEnabledMaterial = conf.getString("items.host-menu.twist-enabled-material");
        hostMenuTwistEnabledDisplayname = conf.getString("items.host-menu.twist-enabled-displayname");
        hostMenuTwistEnabledLore = conf.getStringList("items.host-menu.twist-enabled-lore");
        hostMenuTwistDisabledMaterial = conf.getString("items.host-menu.twist-disabled-material");
        hostMenuTwistDisabledDisplayname = conf.getString("items.host-menu.twist-disabled-displayname");
        hostMenuTwistDisabledLore = conf.getStringList("items.host-menu.twist-disabled-lore");
        hostMenuDaylightCycleEnabledMaterial = conf.getString("items.host-menu.daylight-cycle-enabled-material");
        hostMenuDaylightCycleEnabledDisplayname = conf.getString("items.host-menu.daylight-cycle-enabled-displayname");
        hostMenuDaylightCycleEnabledLore = conf.getStringList("items.host-menu.daylight-cycle-enabled-lore");
        hostMenuDaylightCycleDisabledMaterial = conf.getString("items.host-menu.daylight-cycle-disabled-material");
        hostMenuDaylightCycleDisabledDisplayname = conf.getString("items.host-menu.daylight-cycle-disabled-displayname");
        hostMenuDaylightCycleDisabledLore = conf.getStringList("items.host-menu.daylight-cycle-disabled-lore");
        hostMenuHeadstartMaterial = conf.getString("items.host-menu.headstart-material");
        hostMenuHeadstartDisplayname = conf.getString("items.host-menu.headstart-displayname");
        hostMenuHeadstartLore = conf.getStringList("items.host-menu.headstart-lore");
        hostMenuHeadstartLockedLore = conf.getStringList("items.host-menu.headstart-locked-lore");
        hostMenuManageRunnersMaterial = conf.getString("items.host-menu.manage-runners-material");
        hostMenuManageRunnersDisplayname = conf.getString("items.host-menu.manage-runners-displayname");
        hostMenuManageRunnersLore = conf.getStringList("items.host-menu.manage-runners-lore");
        hostMenuManageRunnersLockedLore = conf.getStringList("items.host-menu.manage-runners-locked-lore");
        hostMenuFriendlyFireEnabledMaterial = conf.getString("items.host-menu.friendly-fire-enabled-material");
        hostMenuFriendlyFireEnabledDisplayname = conf.getString("items.host-menu.friendly-fire-enabled-displayname");
        hostMenuFriendlyFireEnabledLore = conf.getStringList("items.host-menu.friendly-fire-enabled-lore");
        hostMenuFriendlyFireDisabledMaterial = conf.getString("items.host-menu.friendly-fire-disabled-material");
        hostMenuFriendlyFireDisabledDisplayname = conf.getString("items.host-menu.friendly-fire-disabled-displayname");
        hostMenuFriendlyFireDisabledLore = conf.getStringList("items.host-menu.friendly-fire-disabled-lore");
        hostMenuPlayerAmountMaterial = conf.getString("items.host-menu.player-amount-material");
        hostMenuPlayerAmountDisplayname = conf.getString("items.host-menu.player-amount-displayname");
        hostMenuPlayerAmountLockedLore = conf.getStringList("items.host-menu.player-amount-locked-lore");
        hostMenuPlayerAmountLore = conf.getStringList("items.host-menu.player-amount-lore");
        gamesMenuGameHostDisplayname = conf.getString("items.games-menu.game-host-displayname");
        gamesMenuGameHostLore = conf.getStringList("items.games-menu.game-host-lore");
        gamesMenuGameHostLockedLore = conf.getStringList("items.games-menu.game-host-locked-lore");
        headstartMenuHalfMinuteHeadstartMaterial = conf.getString("items.headstart-menu.half-minute-headstart-material");
        headstartMenuHalfMinuteHeadstartDisplayname = conf.getString("items.headstart-menu.half-minute-headstart-displayname");
        headstartMenuOneMinuteHeadstartMaterial = conf.getString("items.headstart-menu.one-minute-headstart-material");
        headstartMenuOneMinuteHeadstartDisplayname = conf.getString("items.headstart-menu.one-minute-headstart-displayname");
        headstartMenuOneHalfMinuteHeadstartMaterial = conf.getString("items.headstart-menu.one-half-minute-headstart-material");
        headstartMenuOneHalfMinuteHeadstartDisplayname = conf.getString("items.headstart-menu.one-half-minute-headstart-displayname");
        headstartMenuTwoMinutesHeadstartMaterial = conf.getString("items.headstart-menu.two-minutes-headstart-material");
        headstartMenuTwoMinutesHeadstartDisplayname = conf.getString("items.headstart-menu.two-minutes-headstart-displayname");
        headstartMenuHeadstartLore = conf.getStringList("items.headstart-menu.headstart-lore");
        headstartMenuSaveMaterial = conf.getString("items.headstart-menu.save-material");
        headstartMenuSaveDisplayname = conf.getString("items.headstart-menu.save-displayname");
        headstartMenuSaveLore = conf.getStringList("items.headstart-menu.save-lore");
        maxHuntersMenuSaveMaterial = conf.getString("items.max-hunters-menu.save-material");
        maxHuntersMenuSaveDisplayname = conf.getString("items.max-hunters-menu.save-displayname");
        maxHuntersMenuSaveLore = conf.getStringList("items.max-hunters-menu.save-lore");
        maxHuntersMenuAddDisplayname = conf.getString("items.max-hunters-menu.add-displayname");
        maxHuntersMenuAddLore = conf.getStringList("items.max-hunters-menu.add-lore");
        maxHuntersMenuRemoveDisplayname = conf.getString("items.max-hunters-menu.remove-displayname");
        maxHuntersMenuRemoveLore = conf.getStringList("items.max-hunters-menu.remove-lore");
        runnerManagerMenuGeneralRunnerDisplayname = conf.getString("items.runner-manager-menu.general-runner-displayname");
        runnerManagerMenuGeneralRunnerLore = conf.getStringList("items.runner-manager-menu.general-runner-lore");
        runnerManagerMenuHostRunnerDisplayname = conf.getString("items.runner-manager-menu.host-runner-displayname");
        runnerManagerMenuHostRunnerLore = conf.getStringList("items.runner-manager-menu.host-runner-lore");
        runnerManagerMenuAddRunnerMaterial = conf.getString("items.runner-manager-menu.add-runner-material");
        runnerManagerMenuAddRunnerDisplayname = conf.getString("items.runner-manager-menu.add-runner-displayname");
        runnerManagerMenuAddRunnerLore = conf.getStringList("items.runner-manager-menu.add-runner-lore");
        runnerManagerMenuSaveMaterial = conf.getString("items.runner-manager-menu.save-material");
        runnerManagerMenuSaveDisplayname = conf.getString("items.runner-manager-menu.save-displayname");
        runnerManagerMenuSaveLore = conf.getStringList("items.runner-manager-menu.save-lore");
        twistVoteMenuHardcoreMaterial = conf.getString("items.twist-vote-menu.hardcore-material");
        twistVoteMenuHardcoreDisplayname = conf.getString("items.twist-vote-menu.hardcore-displayname");
        twistVoteMenuHardcoreLore = conf.getStringList("items.twist-vote-menu.hardcore-lore");
        twistVoteMenuExtraHealthMaterial = conf.getString("items.twist-vote-menu.extra-health-material");
        twistVoteMenuExtraHealthDisplayname = conf.getString("items.twist-vote-menu.extra-health-displayname");
        twistVoteMenuExtraHealthLore = conf.getStringList("items.twist-vote-menu.extra-health-lore");
        twistVoteMenuBlindnessMaterial = conf.getString("items.twist-vote-menu.blindness-material");
        twistVoteMenuBlindnessDisplayname = conf.getString("items.twist-vote-menu.blindness-displayname");
        twistVoteMenuBlindnessLore = conf.getStringList("items.twist-vote-menu.blindness-lore");
        twistVoteMenuRandomYeetMaterial = conf.getString("items.twist-vote-menu.random-yeet-material");
        twistVoteMenuRandomYeetDisplayname = conf.getString("items.twist-vote-menu.random-yeet-displayname");
        twistVoteMenuRandomYeetLore = conf.getStringList("items.twist-vote-menu.random-yeet-lore");
        twistVoteMenuSpeedBoostMaterial = conf.getString("items.twist-vote-menu.speed-boost-material");
        twistVoteMenuSpeedBoostDisplayname = conf.getString("items.twist-vote-menu.speed-boost-displayname");
        twistVoteMenuSpeedBoostLore = conf.getStringList("items.twist-vote-menu.speed-boost-lore");
        twistVoteMenuNoneMaterial = conf.getString("items.twist-vote-menu.none-material");
        twistVoteMenuNoneDisplayname = conf.getString("items.twist-vote-menu.none-displayname");
        twistVoteMenuNoneLore = conf.getStringList("items.twist-vote-menu.none-lore");
        twistVoteMenuAcidRainMaterial = conf.getString("items.twist-vote-menu.acid-rain-material");
        twistVoteMenuAcidRainDisplayname = conf.getString("items.twist-vote-menu.acid-rain-displayname");
        twistvoteMenuAcidRainLore = conf.getStringList("items.twist-vote-menu.acid-rain-lore");
        teleporterMenuPlayerDisplayname = conf.getString("items.teleporter-menu.player-displayname");
        teleporterMenuPlayerLore = conf.getStringList("items.teleporter-menu.player-lore");
        trackerMenuPlayerDisplayname = conf.getString("items.tracker-menu.player-displayname");
        trackerMenuPlayerLore = conf.getStringList("items.tracker-menu.player-lore");

        generalFillMaterial = conf.getString("items.general.fill-material");
        generalCloseMaterial = conf.getString("items.general.close-material");
        gamesMenuNoGamesMaterial = conf.getString("items.games-menu.no-games-material");
        gamesMenuHostGameMaterial = conf.getString("items.games-menu.host-game-material");
        gamesMenuHostUnsupportedProtocolMaterial = conf.getString("items.games-menu.host-game-unsupported-protocol-material");

        hostMenuFinishMaterial = conf.getString("items.host-menu.finish-material");
        hostMenuStartMaterial = conf.getString("items.host-menu.start-material");
        generalTrackerMaterial = conf.getString("items.general.tracker-material");
        generalLeaveMaterial = conf.getString("items.general.leave-material");
        generalTwistVoteMaterial = conf.getString("items.general.twist-vote-material");
        generalSettingsMaterial = conf.getString("items.general.settings-material");
        generalCloseDisplayname = conf.getString("items.general.close-displayname");
        gamesMenuNoGamesDisplayname = conf.getString("items.games-menu.no-games-displayname");
        gamesMenuHostGameDisplayname = conf.getString("items.games-menu.host-game-displayname");
        gamesMenuHostUnsupportedProtocolDisplayname = conf.getString("items.games-menu.host-game-unsupported-protocol-displayname");

        hostMenuFinishDisplayname = conf.getString("items.host-menu.finish-displayname");
        hostMenuStartDisplayname = conf.getString("items.host-menu.start-displayname");
        generalTrackerDisplayname = conf.getString("items.general.tracker-displayname");
        generalLeaveDisplayname = conf.getString("items.general.leave-displayname");
        generalTwistVoteDisplayname = conf.getString("items.general.twist-vote-displayname");
        generalSettingsDisplayname = conf.getString("items.general.settings-displayname");
        generalCloseLore = conf.getStringList("items.general.close-lore");
        gamesMenuNoGamesLore = conf.getStringList("items.games-menu.no-games-lore");
        gamesMenuHostGameLore = conf.getStringList("items.games-menu.host-game-lore");
        gamesMenuHostUnsupportedProtocolLore = conf.getStringList("items.games-menu.host-game-unsupported-protocol-lore");

        hostMenuFinishLore = conf.getStringList("items.host-menu.finish-lore");
        hostMenuStartLore = conf.getStringList("items.host-menu.start-lore");
        generalTrackerLore = conf.getStringList("items.general.tracker-lore");
        generalLeaveLore = conf.getStringList("items.general.leave-lore");
        generalTwistVoteLore = conf.getStringList("items.general.twist-vote-lore");
        generalSettingsLore = conf.getStringList("items.general.settings-lore");

    }

    public void save() {
        conf.set("debug", debug);
        conf.set("disable_setting_changing", disableSettingsChanging);
        conf.set("bungee.enabled", bungeeMode);
        conf.set("bungee.is-lobby", isLobbyServer);
        conf.set("bungee.server-name", serverName);
        conf.set("bungee.game-servers", gameServers);
        conf.set("bungee.socket.hostname", socketHostname);
        conf.set("bungee.socket.port", socketPort);
        conf.set("bungee.lobby-server-name", lobbyServerName);
        conf.set("join-game-on-server-join", joinGameOnServerJoin);
        conf.set("teleport-lobby-on-server-join", teleportLobbyOnServerJoin);
        conf.set("announce-twist-vote-to-entire-game", announceTwistVoteToEntireGame);
        conf.set("teleport-players-to-lobby-in-void", teleportPlayersToLobbyInVoid);
        conf.set("lobby-teleport-void-y-coord", lobbyTeleportYCoord);
        conf.set("auto-join-online-players-when-game-created", autoJoinOnlinePlayersWhenGameCreated);
        conf.set("chunky-generation-size", gensizechunks);
        conf.set("minimum_client_protocol_version", minimumClientProtocolVersion);
        conf.set("price-per-game", pricePerGame);
        conf.set("send-game-host-announcement", sendGameHostAnnouncement);
        conf.set("send-game-announcement-to-lobby-only", sendGameHostAnnouncementToLobbyOnly);
        conf.set("stop-server-after-game", stopServerAfterGame);
        conf.set("minimum-players-per-game", minimumPlayers);
        conf.set("maximum-players-per-game", maximumPlayers);
        conf.set("hunter-lives", hunterLives);
        conf.set("use-uuids-as-world-names", useUuidsAsWorldNames);
        conf.set("disable-advancement-announcing", disableAdvancementAnnouncing);
        conf.set("cancel-lobby-interactions", cancelLobbyInteractions);

        conf.set("rewards.kill", killRewards);
        conf.set("rewards.win", winRewards);
        conf.set("rewards.lose", loseRewards);
        conf.set("rewards.top-three", topThreeRewards);

        conf.set("default_settings.allow_twists", defaultOptionAllowTwists);
        conf.set("default_settings.max_players", defaultOptionMaxPlayers);
        conf.set("default_settings.allow_friendly_fire", defaultOptionAllowFriendlyFire);
        conf.set("default_settings.do_daylight_cycle", defaultOptionDoDaylightCycle);
        conf.set("default_settings.headstart", defaultOptionHeadstart.name());

        conf.set("seeds", seeds);
        conf.set("lobby", lobby);

        conf.set("storage.type", storageType);
        conf.set("storage.database.hostname", databaseHostname);
        conf.set("storage.database.username", databaseUsername);
        conf.set("storage.database.password", databasePassword);
        conf.set("storage.database.database", databaseDatabase);

        conf.set("world-border.enable", enableWorldBorder);
        conf.set("world-border.size", worldBorderSize);
        conf.set("world-border.damage-amount", worldBorderDamage);
        conf.set("world-border.damage-buffer", worldBorderDamageBuffer);
        conf.set("world-border.warning-distance", worldBorderWarningDistance);
        conf.set("world-border.warning-time", worldBorderWarningTime);

        conf.set("chat.enable-lobby-chat", enableLobbyChat);
        conf.set("chat.per-team", chatPerTeam);
        conf.set("chat.separate-dead-chat", separateDeadChat);
        conf.set("chat.format", chatFormat);
        conf.set("chat.lobby-format", lobbyChatFormat);
        conf.set("chat.spectators-have-general-color", spectatorsHaveGeneralColor);

        conf.set("messages.addlife-player", addLifeMessage);
        conf.set("messages.removelife-player", removeLifeMessage);
        conf.set("messages.revived-player", revivedPlayerMessage);
        conf.set("messages.finished-preparing-server", finishedPreparingServerMessage);
        conf.set("messages.server-found", serverFoundMessage);
        conf.set("messages.creating-game-error", creatingGameErrorMessage);
        conf.set("messages.cannot-host-game-invalid-version", cannotHostGameInvalidVersionMessage);
        conf.set("messages.cannot-join-game-invalid-version", cannotJoinGameInvalidVersionMessage);
        conf.set("messages.main-menu-click-store-item", mainMenuClickStoreItemMessage);
        conf.set("messages.game-submitted", gameSubmittedMessage);
        conf.set("messages.free-game-hosted", freeGameHostedMessage);
        conf.set("messages.money-paid-hosting-game", moneyPaidHostingGameMessage);
        conf.set("messages.not-enough-money-hosting-game", notEnoughMoneyHostingGameMessage);
        conf.set("messages.no-permission-hosting-game", noPermissionHostingGameMessage);
        conf.set("messages.money-refunded-no-servers", moneyRefundedNoServersMessage);
        conf.set("messages.no-servers-available", noServersAvailableMessage);
        conf.set("messages.new-host-assigned", newHostAssignedMessage);
        conf.set("messages.game-host-announcement", gameHostAnnouncementMessage);
        conf.set("messages.join-fail", joinFailMessage);
        conf.set("messages.game-joined", gameJoinMessage);
        conf.set("messages.game-left", gameLeftMessage);
        conf.set("messages.game-host-left", gameHostLeftMessage);
        conf.set("messages.player-left-playing", playerLeftPlayingMessage);
        conf.set("messages.player-left-waiting", playerLeftWaitingMessage);
        conf.set("messages.game-end.draw", gameEndDrawMessage);
        conf.set("messages.game-end.win", gameEndWinMessage);
        conf.set("messages.game-end.lose", gameEndLoseMessage);
        conf.set("messages.not-ingame", notIngameMessage);
        conf.set("messages.compass-unavailable", compassUnavailableMessage);
        conf.set("messages.compass-already-added", compassAlreadyAddedMessage);
        conf.set("messages.compass-given", compassGivenMessage);
        conf.set("messages.lobby-set", lobbySetMessage);
        conf.set("messages.not-while-playing", notWhilePlayingMessage);
        conf.set("messages.invalid-game-id", invalidGameIdMessage);
        conf.set("messages.game-already-stopping", gameAlreadyStoppingMessage);
        conf.set("messages.game-must-be-playing", gameMustBePlayingMessage);
        conf.set("messages.game-must-be-waiting", gameMustBeWaitingMessage);
        conf.set("messages.something-went-wrong", somethingWentWrong);
        conf.set("messages.command-no-host", commandNoHostMessage);
        conf.set("messages.stopping-game", stoppingGameMessage);
        conf.set("messages.starting-game", startingGameMessage);
        conf.set("messages.twist-already-active", twistAlreadyActiveMessage);
        conf.set("messages.force-started-twist", twistForcedMessage);
        conf.set("messages.player-not-online", playerNotOnlineMessage);
        conf.set("messages.player-is-you", playerIsYouMessage);
        conf.set("messages.target-player-not-ingame", targetPlayerNotIngameMessage);
        conf.set("messages.target-player-already-runner", targetPlayerAlreadyRunnerMessage);
        conf.set("messages.player-addrunner", playerAddRunnerMessage);
        conf.set("messages.player-removerunner", playerRemoveRunnerMessage);
        conf.set("messages.target-player-no-runner", targetPlayerNoRunner);
        conf.set("messages.no-game-to-rejoin", noGameToRejoinMessage);
        conf.set("messages.already-in-game-rejoin", alreadyInGameRejoinMessage);
        conf.set("messages.rejoin-fail", rejoinFailMessage);
        conf.set("messages.player-rejoined", playerRejoinedMessage);
        conf.set("messages.dragon-defeated", dragonDefeatedMessage);
        conf.set("messages.runner-down", runnerDownMessage);
        conf.set("messages.tracker-reset-died", trackerResetDiedMessage);
        conf.set("messages.runner-entered-nether", runnerEnteredNetherMessage);
        conf.set("messages.runner-entered-end", runnerEnteredEndMessage);
        conf.set("messages.delayed-leave-start", delayedLeaveStartMessage);
        conf.set("messages.delayed-leave-cancel", delayedLeaveCancelMessage);
        conf.set("messages.player-left-game", playerLeftGameMessage);
        conf.set("messages.player-twist-voted", playerTwistVoteMessage);
        conf.set("messages.twist-voted", twistVotedMessage);
        conf.set("messages.runner-added", runnerAddedMessage);
        conf.set("messages.runner-removed", runnerRemovedMessage);
        conf.set("messages.respawned-bed", respawnedBedMessage);
        conf.set("messages.thanks-for-playing", thanksForPlaying);
        conf.set("messages.hunter-release-countdown", hunterReleaseCountdownMessage);
        conf.set("messages.starting-countdown", startingCountdownMessage);
        conf.set("messages.hunters-released", huntersReleasedMessage);
        conf.set("messages.game-start-runner", gameStartRunnerMessage);
        conf.set("messages.game-start-hunter", gameStartHunterMessage);
        conf.set("messages.twist-select", twistSelectMessage);
        conf.set("messages.twists.random-yeet", twistRandomYeetMessage);
        conf.set("messages.twists.speed-boost", twistSpeedBoostMessage);
        conf.set("messages.twists.blindness", twistBlindnessMessage);
        conf.set("messages.twists.acid-rain", twistAcidRainMessage);
        conf.set("messages.twists.acid-rain-ended", twistAcidRainEndedMessage);
        conf.set("messages.twists.hardcore", twistHardcoreMessage);
        conf.set("messages.twists.hardcore-ended", twistHardcoreEndedMessage);
        conf.set("messages.headstart-change", headstartChangeMessage);
        conf.set("messages.toggle-twists-enabled", toggleTwistsEnabledMessage);
        conf.set("messages.toggle-twists.disabled", toggleTwistsDisabledMessage);
        conf.set("messages.toggle-daylight-enabled", toggleDaylightEnabledMessage);
        conf.set("messages.toggle-daylight-disabled", toggleDaylightDisabledMessage);
        conf.set("messages.toggle-friendly-fire-enabled", toggleFriendlyFireEnabledMessage);
        conf.set("messages.toggle-friendly-fire-disabled", toggleFriendlyFireDisabledMessage);
        conf.set("messages.tracking-player", trackingPlayerMessage);
        conf.set("messages.teleporting-player", teleportingPlayerMessage);
        conf.set("messages.failed-tracking", failedTrackingMessage);
        conf.set("messages.failed-teleporting", failedTeleportingMessage);
        conf.set("messages.game-created", gameCreatedMessage);
        conf.set("messages.already-own-game", alreadyOwnGameMessage);
        conf.set("messages.game-discard", gameDiscardMessage);
        conf.set("messages.game-unavailable", gameUnavailableMessage);
        conf.set("messages.runner-add-cancelled", runnerAddCancelledMessage);
        conf.set("messages.runner-add-try-again", runnerAddTryAgainMessage);
        conf.set("messages.runner-add-instructions", runnerAddInstructionsMessage);
        conf.set("messages.menu-runner-manager-cannot-remove-host", menuRunnerManagerCannotRemoveHostMessage);
        conf.set("messages.menu-runner-manager-cannot-remove-runner", menuRunnerManagerCannotRemoveRunnerMessage);
        conf.set("messages.cannot-leave-waiting-zone", cannotLeaveWaitingZoneMessage);
        conf.set("messages.cannot-leave-lobby", cannotLeaveLobbyMessage);
        conf.set("messages.auto-rejoin", autoRejoinMessage);
        conf.set("messages.stats-message", statsMessage);
        conf.set("messages.money-refunded", moneyRefundedMessage);

        conf.set("menus.tracker-title", menuTrackerTitle);
        conf.set("menus.teleporter-title", menuTeleporterTitle);
        conf.set("menus.events-title", menuEventsTitle);
        conf.set("menus.host-title", menuHostTitle);
        conf.set("menus.games-title", menuGamesTitle);
        conf.set("menus.headstart-title", menuHeadstartTitle);
        conf.set("menus.max-hunters-title", menuMaxHuntersTitle);
        conf.set("menus.runner-manager-title", menuRunnerManagerTitle);
        conf.set("menus.twist-vote-title", menuTwistVoteTitle);
        conf.set("menus.main-title", mainMenuTitle);

        conf.set("actionbar.tracking-portal", trackingPortalActionbar);
        conf.set("actionbar.tracking-other-dimension", trackingOtherDimensionActionbar);
        conf.set("actionbar.tracking", trackingActionbar);
        conf.set("actionbar.respawned-worldspawn", respawnedWorldspawnActionbar);
        conf.set("actionbar.respawned-bed", respawnedBedActionbar);

        conf.set("prefixes.nametags.runner", runnerNametagPrefix);
        conf.set("prefixes.nametags.hunter", hunterNametagPrefix);
        conf.set("prefixes.lobby", lobbyChatPrefix);
        conf.set("prefixes.global", globalChatPrefix);
        conf.set("prefixes.runner", runnerChatPrefix);
        conf.set("prefixes.hunter", hunterChatPrefix);
        conf.set("prefixes.dead", deadChatPrefix);
        conf.set("prefixes.runner-color", runnerColor);
        conf.set("prefixes.hunter-color", hunterColor);
        conf.set("prefixes.spectator-color", spectatorChatColor);
        conf.set("prefixes.status.loading", loadingStatusPrefix);
        conf.set("prefixes.status.starting", startingStatusPrefix);
        conf.set("prefixes.status.playing", playingStatusPrefix);
        conf.set("prefixes.status.waiting", waitingStatusPrefix);
        conf.set("prefixes.status.stopping", stoppingStatusPrefix);
        conf.set("prefixes.selected", selectedPrefix);

        conf.set("titles.server-found", serverFoundTitle);
        conf.set("titles.searching-server", searchingServerTitle);
        conf.set("titles.no-servers-available", noServersAvailableTitle);
        conf.set("titles.new-host-assigned", newHostAssignedTitle);
        conf.set("titles.game-end.draw", gameEndDrawTitle);
        conf.set("titles.game-end.win-runner", gameEndWinRunnerTitle);
        conf.set("titles.game-end.win-hunter", gameEndWinHunterTitle);
        conf.set("titles.game-end.lose-runner", gameEndLoseRunnerTitle);
        conf.set("titles.game-end.lose-hunter", gameEndLoseHunterTitle);
        conf.set("titles.game-end.win-runner-dragon", gameEndWinRunnerDragonTitle);
        conf.set("titles.dragon-defeated", dragonDefeatedTitle);
        conf.set("titles.death", deathTitle);
        conf.set("titles.runner-down", runnerDownTitle);
        conf.set("titles.player-entered-nether", playerEnteredNetherTitle);
        conf.set("titles.player-entered-end", playerEnteredEndTitle);
        conf.set("titles.runner-added", runnerAddedTitle);
        conf.set("titles.respawning-soon", respawningSoonTitle);
        conf.set("titles.hunter-release-countdown", hunterReleaseCountdownTitle);
        conf.set("titles.hunters-released-hunter", huntersReleasedHunterTitle);
        conf.set("titles.hunters-released-runner", huntersReleasedRunnerTitle);
        conf.set("titles.starting-countdown", startingCountdownTitle);
        conf.set("titles.game-start-hunter", gameStartHunterTitle);
        conf.set("titles.game-start-runner", gameStartRunnerTitle);
        conf.set("titles.twists.random-yeet", twistRandomYeetTitle);
        conf.set("titles.twists.speed-boost", twistSpeedBoostTitle);
        conf.set("titles.twists.blindness", twistBlindnessTitle);
        conf.set("titles.twists.acid-rain", twistAcidRainTitle);
        conf.set("titles.twists.hardcore", twistHardcoreTitle);

        conf.set("scoreboards.title", scoreboardTitle);
        conf.set("scoreboards.loading", loadingScoreboard);
        conf.set("scoreboards.waiting", waitingScoreboard);
        conf.set("scoreboards.waiting-host", waitingHostScoreboard);
        conf.set("scoreboards.starting-runner", startingRunnerScoreboard);
        conf.set("scoreboards.starting-hunter", startingHunterScoreboard);
        conf.set("scoreboards.playing-unreleased-hunter", playingUnreleasedHunterScoreboard);
        conf.set("scoreboards.playing-unreleased-runner", playingUnreleasedRunnerScoreboard);
        conf.set("scoreboards.playing", playingScoreboard);
        conf.set("scoreboards.stopping-draw", stoppingDrawScoreboard);
        conf.set("scoreboards.stopping-win", stoppingWinScoreboard);
        conf.set("scoreboards.stopping-lose", stoppingLoseScoreboard);

        conf.set("sounds.cant-host-game", cantHostGameSound);
        conf.set("sounds.no-servers-available", noServersAvailableSound);
        conf.set("sounds.searching-server-ticking", searchingServerTickingSound);
        conf.set("sounds.new-host-assigned", newHostAssignedSound);
        conf.set("sounds.game-host-announcement", gameHostAnnouncementSound);
        conf.set("sounds.game-end.draw", gameEndDrawSound);
        conf.set("sounds.game-end.win", gameEndWinSound);
        conf.set("sounds.game-end.lose", gameEndLoseSound);
        conf.set("sounds.runner-entered-nether", runnerEnteredNetherSound);
        conf.set("sounds.runner-entered-end", runnerEnteredEndSound);
        conf.set("sounds.delayed-leave-start", delayedLeaveStartSound);
        conf.set("sounds.delayed-leave-cancel", delayedLeaveCancelSound);
        conf.set("sounds.player-respawned", playerRespawnedSound);
        conf.set("sounds.countdown", countdownSound);
        conf.set("sounds.hunters-released", huntersReleasedSound);
        conf.set("sounds.twists.random-yeet", twistRandomYeetSound);
        conf.set("sounds.twists.speed-boost", twistSpeedBoostSound);
        conf.set("sounds.twists.blindness", twistBlindnessSound);
        conf.set("sounds.twists.acid-rain", twistAcidRainSound);
        conf.set("sounds.twists.hardcore", twistHardcoreSound);
        conf.set("sounds.open-menu-host-game", openMenuHostGameSound);
        conf.set("sounds.close-menu-host-game", closeMenuHostGameSound);
        conf.set("sounds.menu-host-toggle-twist", menuHostToggleTwistSound);
        conf.set("sounds.menu-host-toggle-daylight", menuHostToggleDaylightSound);
        conf.set("sounds.menu-host-toggle-friendly-fire", menuHostToggleFriendlyFireSound);
        conf.set("sounds.menu-host-locked", menuHostLockedSound);
        conf.set("sounds.menu-host-game-started", menuHostGameStartedSound);
        conf.set("sounds.menu-headstart-select", menuHeadstartSelectSound);
        conf.set("sounds.menu-headstart-save", menuHeadstartSaveSound);
        conf.set("sounds.open-menu-headstart", openMenuHeadstartSound);
        conf.set("sounds.menu-max-hunters-change-amount", menuMaxHuntersChangeAmountSound);
        conf.set("sounds.menu-runner-manager-cannot-remove-host", menuRunnerManagerCannotRemoveHostSound);
        conf.set("sounds.menu-runner-manager-cannot-remove-runner", menuRunnerManagerCannotRemoveRunnerSound);
        conf.set("sounds.runner-removed", runnerRemovedSound);
        conf.set("sounds.twist-vote", twistVoteSound);
        conf.set("sounds.open-twist-vote-menu", openTwistVoteMenuSound);
        conf.set("sounds.main-menu-click-store-item", mainMenuClickStoreItemSound);

        conf.set("items.twist-vote-menu.option-disabled-material", twistVoteMenuOptionDisabledMaterial);
        conf.set("items.twist-vote-menu.option-disabled-displayname", twistVoteMenuOptionDisabledDisplayname);
        conf.set("items.twist-vote-menu.option-disabled-lore", twistVoteMenuOptionDisabledLore);
        conf.set("items.general.go-back-material", generalGoBackMaterial);
        conf.set("items.general.go-back-displayname", generalGoBackDisplayname);
        conf.set("items.general.go-back-lore", generalGoBackLore);

        conf.set("items.main-menu.host-game-can-host-material", mainMenuHostGameCanHostMaterial);
        conf.set("items.main-menu.host-game-can-host-displayname", mainMenuHostGameCanHostDisplayname);
        conf.set("items.main-menu.host-game-can-host-lore", mainMenuHostGameCanHostLore);
        conf.set("items.main-menu.host-game-cannot-host-material", mainMenuHostGameCannotHostMaterial);
        conf.set("items.main-menu.host-game-cannot-host-displayname", mainMenuHostGameCannotHostDisplayname);
        conf.set("items.main-menu.host-game-cannot-host-lore", mainMenuHostGameCannotHostLore);
        conf.set("items.main-menu.host-game-invalid-version-material", mainMenuHostGameInvalidVersionMaterial);
        conf.set("items.main-menu.host-game-invalid-version-displayname", mainMenuHostGameInvalidVersionDisplayname);
        conf.set("items.main-menu.host-game-invalid-version-lore", mainMenuHostGameInvalidVersionLore);
        conf.set("items.main-menu.join-game-material", mainMenuJoinGameMaterial);
        conf.set("items.main-menu.join-game-displayname", mainMenuJoinGameDisplayname);
        conf.set("items.main-menu.join-game-lore", mainMenuJoinGameLore);
        conf.set("items.main-menu.join-game-invalid-version-material", mainMenuJoinGameInvalidVersionMaterial);
        conf.set("items.main-menu.join-game-invalid-version-displayname", mainMenuJoinGameInvalidVersionDisplayname);
        conf.set("items.main-menu.join-game-invalid-version-lore", mainMenuJoinGameInvalidVersionLore);
        conf.set("items.main-menu.store-material", mainMenuStoreMaterial);
        conf.set("items.main-menu.store-displayname", mainMenuStoreDisplayname);
        conf.set("items.main-menu.store-lore", mainMenuStoreLore);

        conf.set("items.main-menu.balance-info-enough-material", mainMenuBalanceInfoEnoughMaterial);
        conf.set("items.main-menu.balance-info-enough-displayname", mainMenuBalanceInfoEnoughDisplayname);
        conf.set("items.main-menu.balance-info-enough-lore", mainMenuBalanceInfoEnoughLore);
        conf.set("items.main-menu.balance-info-not-enough-material", mainMenuBalanceInfoNotEnoughMaterial);
        conf.set("items.main-menu.balance-info-not-enough-displayname", mainMenuBalanceInfoNotEnoughDisplayname);
        conf.set("items.main-menu.balance-info-not-enough-lore", mainMenuBalanceInfoNotEnoughLore);
        conf.set("items.event-menu.manhunt-material", eventMenuManhuntMaterial);
        conf.set("items.event-menu.manhunt-displayname", eventMenuManhuntDisplayname);
        conf.set("items.event-menu.manhunt-lore", eventMenuManhuntLore);
        conf.set("items.host-menu.twist-enabled-material", hostMenuTwistEnabledMaterial);
        conf.set("items.host-menu.twist-enabled-displayname", hostMenuTwistEnabledDisplayname);
        conf.set("items.host-menu.twist-enabled-lore", hostMenuTwistEnabledLore);
        conf.set("items.host-menu.twist-disabled-material", hostMenuTwistDisabledMaterial);
        conf.set("items.host-menu.twist-disabled-displayname", hostMenuTwistDisabledDisplayname);
        conf.set("items.host-menu.twist-disabled-lore", hostMenuTwistDisabledLore);
        conf.set("items.host-menu.daylight-cycle-enabled-material", hostMenuDaylightCycleEnabledMaterial);
        conf.set("items.host-menu.daylight-cycle-enabled-displayname", hostMenuDaylightCycleEnabledDisplayname);
        conf.set("items.host-menu.daylight-cycle-enabled-lore", hostMenuDaylightCycleEnabledLore);
        conf.set("items.host-menu.daylight-cycle-disabled-material", hostMenuDaylightCycleDisabledMaterial);
        conf.set("items.host-menu.daylight-cycle-disabled-displayname", hostMenuDaylightCycleDisabledDisplayname);
        conf.set("items.host-menu.daylight-cycle-disabled-lore", hostMenuDaylightCycleDisabledLore);
        conf.set("items.host-menu.headstart-material", hostMenuHeadstartMaterial);
        conf.set("items.host-menu.headstart-displayname", hostMenuHeadstartDisplayname);
        conf.set("items.host-menu.headstart-lore", hostMenuHeadstartLore);
        conf.set("items.host-menu.headstart-locked-lore", hostMenuHeadstartLockedLore);
        conf.set("items.host-menu.manage-runners-material", hostMenuManageRunnersMaterial);
        conf.set("items.host-menu.manage-runners-displayname", hostMenuManageRunnersDisplayname);
        conf.set("items.host-menu.manage-runners-lore", hostMenuManageRunnersLore);
        conf.set("items.host-menu.manage-runners-locked-lore", hostMenuManageRunnersLockedLore);
        conf.set("items.host-menu.friendly-fire-enabled-material", hostMenuFriendlyFireEnabledMaterial);
        conf.set("items.host-menu.friendly-fire-enabled-displayname", hostMenuFriendlyFireEnabledDisplayname);
        conf.set("items.host-menu.friendly-fire-enabled-lore", hostMenuFriendlyFireEnabledLore);
        conf.set("items.host-menu.friendly-fire-disabled-material", hostMenuFriendlyFireDisabledMaterial);
        conf.set("items.host-menu.friendly-fire-disabled-displayname", hostMenuFriendlyFireDisabledDisplayname);
        conf.set("items.host-menu.friendly-fire-disabled-lore", hostMenuFriendlyFireDisabledLore);
        conf.set("items.host-menu.player-amount-material", hostMenuPlayerAmountMaterial);
        conf.set("items.host-menu.player-amount-displayname", hostMenuPlayerAmountDisplayname);
        conf.set("items.host-menu.player-amount-locked-lore", hostMenuPlayerAmountLockedLore);
        conf.set("items.host-menu.player-amount-lore", hostMenuPlayerAmountLore);
        conf.set("items.games-menu.game-host-displayname", gamesMenuGameHostDisplayname);
        conf.set("items.games-menu.game-host-lore", gamesMenuGameHostLore);
        conf.set("items.games-menu.game-host-locked-lore", gamesMenuGameHostLockedLore);
        conf.set("items.headstart-menu.half-minute-headstart-material", headstartMenuHalfMinuteHeadstartMaterial);
        conf.set("items.headstart-menu.half-minute-headstart-displayname", headstartMenuHalfMinuteHeadstartDisplayname);
        conf.set("items.headstart-menu.one-minute-headstart-material", headstartMenuOneMinuteHeadstartMaterial);
        conf.set("items.headstart-menu.one-minute-headstart-displayname", headstartMenuOneMinuteHeadstartDisplayname);
        conf.set("items.headstart-menu.one-half-minute-headstart-material", headstartMenuOneHalfMinuteHeadstartMaterial);
        conf.set("items.headstart-menu.one-half-minute-headstart-displayname", headstartMenuOneHalfMinuteHeadstartDisplayname);
        conf.set("items.headstart-menu.two-minutes-headstart-material", headstartMenuTwoMinutesHeadstartMaterial);
        conf.set("items.headstart-menu.two-minutes-headstart-displayname", headstartMenuTwoMinutesHeadstartDisplayname);
        conf.set("items.headstart-menu.headstart-lore", headstartMenuHeadstartLore);
        conf.set("items.headstart-menu.save-material", headstartMenuSaveMaterial);
        conf.set("items.headstart-menu.save-displayname", headstartMenuSaveDisplayname);
        conf.set("items.headstart-menu.save-lore", headstartMenuSaveLore);
        conf.set("items.max-hunters-menu.save-material", maxHuntersMenuSaveMaterial);
        conf.set("items.max-hunters-menu.save-displayname", maxHuntersMenuSaveDisplayname);
        conf.set("items.max-hunters-menu.save-lore", maxHuntersMenuSaveLore);
        conf.set("items.max-hunters-menu.add-lore", maxHuntersMenuAddLore);
        conf.set("items.max-hunters-menu.add-displayname", maxHuntersMenuAddDisplayname);
        conf.set("items.max-hunters-menu.remove-lore", maxHuntersMenuRemoveLore);
        conf.set("items.max-hunters-menu.remove-displayname", maxHuntersMenuRemoveDisplayname);
        conf.set("items.runner-manager-menu.general-runner-displayname", runnerManagerMenuGeneralRunnerDisplayname);
        conf.set("items.runner-manager-menu.general-runner-lore", runnerManagerMenuGeneralRunnerLore);
        conf.set("items.runner-manager-menu.host-runner-displayname", runnerManagerMenuHostRunnerDisplayname);
        conf.set("items.runner-manager-menu.host-runner-lore", runnerManagerMenuHostRunnerLore);
        conf.set("items.runner-manager-menu.add-runner-material", runnerManagerMenuAddRunnerMaterial);
        conf.set("items.runner-manager-menu.add-runner-displayname", runnerManagerMenuAddRunnerDisplayname);
        conf.set("items.runner-manager-menu.add-runner-lore", runnerManagerMenuAddRunnerLore);
        conf.set("items.runner-manager-menu.save-material", runnerManagerMenuSaveMaterial);
        conf.set("items.runner-manager-menu.save-displayname", runnerManagerMenuSaveDisplayname);
        conf.set("items.runner-manager-menu.save-lore", runnerManagerMenuSaveLore);

        conf.set("items.twist-vote-menu.hardcore-material", twistVoteMenuHardcoreMaterial);
        conf.set("items.twist-vote-menu.hardcore-displayname", twistVoteMenuHardcoreDisplayname);
        conf.set("items.twist-vote-menu.hardcore-lore", twistVoteMenuHardcoreLore);
        conf.set("items.twist-vote-menu.extra-health-material", twistVoteMenuExtraHealthMaterial);
        conf.set("items.twist-vote-menu.extra-health-displayname", twistVoteMenuExtraHealthDisplayname);
        conf.set("items.twist-vote-menu.extra-health-lore", twistVoteMenuExtraHealthLore);
        conf.set("items.twist-vote-menu.blindness-material", twistVoteMenuBlindnessMaterial);
        conf.set("items.twist-vote-menu.blindness-displayname", twistVoteMenuBlindnessDisplayname);
        conf.set("items.twist-vote-menu.blindness-lore", twistVoteMenuBlindnessLore);
        conf.set("items.twist-vote-menu.random-yeet-material", twistVoteMenuRandomYeetMaterial);
        conf.set("items.twist-vote-menu.random-yeet-displayname", twistVoteMenuRandomYeetDisplayname);
        conf.set("items.twist-vote-menu.random-yeet-lore", twistVoteMenuRandomYeetLore);
        conf.set("items.twist-vote-menu.speed-boost-material", twistVoteMenuSpeedBoostMaterial);
        conf.set("items.twist-vote-menu.speed-boost-displayname", twistVoteMenuSpeedBoostDisplayname);
        conf.set("items.twist-vote-menu.speed-boost-lore", twistVoteMenuSpeedBoostLore);
        conf.set("items.twist-vote-menu.none-material", twistVoteMenuNoneMaterial);
        conf.set("items.twist-vote-menu.none-displayname", twistVoteMenuNoneDisplayname);
        conf.set("items.twist-vote-menu.none-lore", twistVoteMenuNoneLore);
        conf.set("items.twist-vote-menu.acid-rain-material", twistVoteMenuAcidRainMaterial);
        conf.set("items.twist-vote-menu.acid-rain-displayname", twistVoteMenuAcidRainDisplayname);
        conf.set("items.twist-vote-menu.acid-rain-lore", twistvoteMenuAcidRainLore);
        conf.set("items.teleporter-menu.player-displayname", teleporterMenuPlayerDisplayname);
        conf.set("items.teleporter-menu.player-lore", teleporterMenuPlayerLore);
        conf.set("items.tracker-menu.player-displayname", trackerMenuPlayerDisplayname);
        conf.set("items.tracker-menu.player-lore", trackerMenuPlayerLore);

        conf.set("items.general.fill-material", generalFillMaterial);
        conf.set("items.general.close-material", generalCloseMaterial);
        conf.set("items.games-menu.no-games-material", gamesMenuNoGamesMaterial);
        conf.set("items.games-menu.host-game-material", gamesMenuHostGameMaterial);
        conf.set("items.games-menu.host-game-unsupported-protocol-material", gamesMenuHostUnsupportedProtocolMaterial);
        conf.set("items.host-menu.finish-material", hostMenuFinishMaterial);
        conf.set("items.host-menu.start-material", hostMenuStartMaterial);
        conf.set("items.general.tracker-material", generalTrackerMaterial);
        conf.set("items.general.leave-material", generalLeaveMaterial);
        conf.set("items.general.twist-vote-material", generalTwistVoteMaterial);
        conf.set("items.general.settings-material", generalSettingsMaterial);
        conf.set("items.general.close-displayname", generalCloseDisplayname);
        conf.set("items.games-menu.no-games-displayname", gamesMenuNoGamesDisplayname);
        conf.set("items.games-menu.host-game-displayname", gamesMenuHostGameDisplayname);
        conf.set("items.games-menu.host-game-unsupported-protocol-displayname", gamesMenuHostUnsupportedProtocolDisplayname);
        conf.set("items.host-menu.finish-displayname", hostMenuFinishDisplayname);
        conf.set("items.host-menu.start-displayname", hostMenuStartDisplayname);
        conf.set("items.general.tracker-displayname", generalTrackerDisplayname);
        conf.set("items.general.leave-displayname", generalLeaveDisplayname);
        conf.set("items.general.twist-vote-displayname", generalTwistVoteDisplayname);
        conf.set("items.general.settings-displayname", generalSettingsDisplayname);
        conf.set("items.general.close-lore", generalCloseLore);
        conf.set("items.games-menu.no-games-lore", gamesMenuNoGamesLore);
        conf.set("items.games-menu.host-game-lore", gamesMenuHostGameLore);
        conf.set("items.games-menu.host-game-unsupported-protocol-lore", gamesMenuHostUnsupportedProtocolLore);
        conf.set("items.host-menu.finish-lore", hostMenuFinishLore);
        conf.set("items.host-menu.start-lore", hostMenuStartLore);
        conf.set("items.general.tracker-lore", generalTrackerLore);
        conf.set("items.general.leave-lore", generalLeaveLore);
        conf.set("items.general.twist-vote-lore", generalTwistVoteLore);
        conf.set("items.general.settings-lore", generalSettingsLore);

        try {
            conf.save(file);
        } catch (IOException e) {
            Manhunt.get().getLogger().severe("Couldn't save the config.yml.");
            e.printStackTrace();
        }
    }

    public FileConfiguration getFile() {
        return conf;
    }
}
